# Linear Systems (Triangular matrix)

In `project3_demo1.ipynb`, we have learned how to use `scipy.linalg.solve` to solve the linear equation $Ax=b$.

In this notebook, we will learn how to solve linear systems step by step. We consider two special matrices first: lower triangular mastrix and upper triagnular matrix. 

References: 
* https://books.google.com.tw/books?id=f6Z8DwAAQBAJ&hl=zh-TW
* https://docs.scipy.org/doc/scipy/reference/linalg.html



In [10]:
import numpy as np
from scipy import linalg # just for checking

## Lower Triagnular Matrix

Implment the solver to solve the solution with a lower trianuglar matrix.

In [11]:
def solveLowerTriangular(L,b):
    """
    Solve a linear system with a lower triangular matrix L.

    Arguments:
    L -- a lower triangular matrix
    b -- a vector

    Returns:
    x -- the solution to the linear system
    """
    n  = len(b)
    x  = np.zeros(n)
    bs = np.copy(b)

    for j in range(n):
        # check if L[i,i] is singular
        if L[j,j] == 0:
            raise ValueError("L[{},{}] is zero".format(i,i))
        x[j] = bs[j]/L[j,j]
        
        for i in range(j,n):
            bs[i] -= L[i,j]*x[j]
    
    return x

## Exercise 1: Lower Triangular Matrix

Write a python progem to solve this lower triangular matrix. Do NOT use `scipy.linalg`. Your lower triangular matrix solver should be general for $N \times N$ matrix.

$$
\begin{bmatrix}
-1 & 0 & 0 \\
-6 & -4 & 0 \\
1 & 2 & 2 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
x_{1} \\
x_2 \\
x_3 \\
\end{bmatrix}
=
\begin{bmatrix}
1 \\
-6 \\
3 \\
\end{bmatrix}
$$

In [12]:
L = np.array([[-1,0,0],[-6,-4,0],[1,2,2]])
b = np.array([1,-6,3])
print(L,b)

[[-1  0  0]
 [-6 -4  0]
 [ 1  2  2]] [ 1 -6  3]


In [13]:
x = solveLowerTriangular(L,b)
print(x)

[-1.  3. -1.]


Check if $$\boldsymbol{L} \cdot \boldsymbol{x} = \boldsymbol{b}$$

In [14]:
# check L x = b
print(np.dot(L,x))
print(b)

[ 1. -6.  3.]
[ 1 -6  3]


In [15]:
# check L^-1 b = x
print(linalg.inv(L).dot(b))
print(x)

[-1.  3. -1.]
[-1.  3. -1.]


In [16]:
# compare with solution from scipy 
print(linalg.solve(L,b))

[-1.  3. -1.]


## Upper Triagnular Matrix

## Exercise: Solving upper trianular matrix

Write a python progem to solve the upper triangular matrix. Do NOT use `scipy.linalg`. Your upper triangular matrix solver should be general for $N \times N$ matrix.

$$
\begin{bmatrix}
1 & 2 & 2 \\
0 & -4 & -6 \\
0 & 0 & -1 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
x_{1} \\
x_2 \\
x_3 \\
\end{bmatrix}
=
\begin{bmatrix}
3 \\
-6 \\
1 \\
\end{bmatrix}
$$

In [17]:
def solveUpperTriangular(U,b):
    """
    Solve a linear system with an upper triangular matrix U.

    Arguments:
    U -- an upper triangular matrix
    b -- a vector

    Returns:
    x -- the solution to the linear system

    """
    n  = len(b)
    x  = np.zeros(n)
    bs = np.copy(b)

    for j in range(n-1,-1,-1):
        # check if U[i,i] is singular
        if U[j,j] == 0:
            raise ValueError("U[{},{}] is zero".format(i,i))
        x[j] = bs[j]/U[j,j]
        
        for i in range(j):
            bs[i] -= U[i,j]*x[j]
    
    return x

In [18]:
U = np.array([[1,2,2],[0,-4,-6],[0,0,-1]])
b = np.array([3,-6,1])
print(U,b)

[[ 1  2  2]
 [ 0 -4 -6]
 [ 0  0 -1]] [ 3 -6  1]


In [19]:
x = solveUpperTriangular(U,b)
print(x)

[-1.  3. -1.]


In [20]:
# check U x = b
print(np.dot(U,x))
print(b)

[ 3. -6.  1.]
[ 3 -6  1]


In [21]:
# check U^-1 b = x
print(linalg.inv(U).dot(b))
print(x)

[-1.  3. -1.]
[-1.  3. -1.]


In [22]:
# compare with solution from scipy
print(linalg.solve(U,b))

[-1.  3. -1.]
