# Linear systems

In [1]:
import numpy as np
from mylinalg import solveLowerTriangular, solveUpperTriangular, lu, lu_solve

# Exercise: LU decomposition

Write a python program to solve it. 
Do not use any linear algebra packackes. 
Use your own linear algebra solvers in `mylinalg.py`.

$$
\boldsymbol{Ax}=
\begin{bmatrix}
2 & 4 & -2 \\
4 & 9 & -3 \\
-2 & -3 & 7 \\
\end{bmatrix}
\cdot
\begin{bmatrix}
x_{1} \\
x_2 \\
x_3 \\
\end{bmatrix}
=
\begin{bmatrix}
2 \\
8 \\
10 \\
\end{bmatrix}
= \boldsymbol{b}
$$

In [2]:
A = [[2,4,-2],[4,9,-3],[-2,-3,7]]

In [3]:
l, u = lu(A)

In [4]:
print(l,u)

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  1.  1.]] [[ 2.  4. -2.]
 [ 0.  1.  1.]
 [ 0.  0.  4.]]


Check $LU = A$

In [5]:
print(np.dot(l,u))
print(A)

[[ 2.  4. -2.]
 [ 4.  9. -3.]
 [-2. -3.  7.]]
[[2, 4, -2], [4, 9, -3], [-2, -3, 7]]


In [6]:
b = np.array([2,8,10])
x = lu_solve(A,b)
print(x)

[-1.  2.  2.]


compare your solution with scipy

In [7]:
from scipy.linalg import lu as scipy_lu
from scipy.linalg import lu_factor as scipy_lu_factor
from scipy.linalg import lu_solve as scipy_lu_solve
from scipy.linalg import solve as scipy_solve

In [9]:
P, L, U = scipy_lu(A)

# A = PLU
print(np.dot(P,np.dot(L,U)))
print(A)

[[ 2.  4. -2.]
 [ 4.  9. -3.]
 [-2. -3.  7.]]
[[2, 4, -2], [4, 9, -3], [-2, -3, 7]]


In [11]:
b = np.array([2,8,10])
lu, piv = scipy_lu_factor(A)
x = scipy_lu_solve((lu, piv), b)
print(x)

[-1.  2.  2.]


In [12]:
x = scipy_solve(A,b)
print(x)

[-1.  2.  2.]


# Apply to the Laplace's equation

Copy your previous codes in `project3_demo1.ipynb` but use your own linear algebra solver.

In [ ]:
import numpy as np
from scipy.sparse import dia_array  # if dia_array is not able, use dia_matrix
from scipy.sparse import dia_matrix
from numba import jit, njit, prange
import matplotlib.pyplot as plt

In [ ]:
# Copy your function from the previous notebook here










In [ ]:
def solve_laplace(N=16):
    u = np.zeros((N,N)) # A place holder for the solution

    # TODO Copy your solver here





    return u

In [ ]:
u = solve_laplace(N=16)

In [ ]:
plt.imshow(u.T,origin="lower")

You could see that our solver is much slower than `scipy.linalg`. Could you speed it up?